spring.application.name=neorios

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/neorios
spring.datasource.username=root
spring.datasource.password=1113784573Sp?

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect